import { Baloo_Tammudu_2 } from "next/font/google"
import "./globals.css"
import Nav from "./(components)/Nav"
import PomodoroNav from "./(components)/PomodoroNav"
import Footer from "./(components)/Footer"
import { Analytics } from "@vercel/analytics/react"

const baloo = Baloo_Tammudu_2({ weight: ["400", "700"], subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={` bg-red`}>
        <Nav />
        <PomodoroNav />
        {children}
        <Analytics />
        <Footer />
      </body>
    </html>
  )
}
